### PR TITLE
`.truncate` to strip html tags, fixes #5

### LINKED ISSUE #5: .truncate does not removes HTML as mentioned
example

``` js
truncate("<span>foo bar baz</span>", 5);
//=> '<span'
```

test would be

``` js
    it('should truncate by removing all HTML tags', function() {
      utils.truncate('<span>foo bar baz</span>', 5).should.equal('foo b');
    });
```

using https://github.com/ericnorris/striptags seems good way to go with

### PR DESCRIPTION
**Pull request by tunnckoCore**
also add one more `.ellipsis` test based on .truncate changes. fixes #5

### CODE REVIEW

**Comment by jonschlinkert** [comment]
thanks!

**Comment by tunnckoCore** [comment]
Cheers. :beers:

**Comment by jonschlinkert** [comment]
published as 0.3.1. thanks again!

**Comment by tunnckoCore** [comment]
btw, suggest you to use `shields.io` for badges everywhere :)

**Comment by jonschlinkert** [comment]
yeah, I am with the next release of verb.

**Pull request merged**
